### PR TITLE
JIRA response will have 'errors' as key

### PR DESCRIPTION
**Pull request by mmkader85**
https://docs.atlassian.com/jira/REST/latest/#api/2/filter-createFilter

### CODE REVIEW

**Comment by aik099** [comment]
So you're saying that actual issues are returned in `errors` key of REST API response?

**Comment by aik099** [comment]
Maybe the request, that's response you're feeding into `Result` class has something wrong in it?

**Comment by mmkader85** [comment]
Yes, if there are any errors then it is returing with the key 'errors' and not 'issues'. See a sample response from JIRA below.


```php
chobie\Jira\Api\Result Object
(
    [expand:protected] =>
    [startAt:protected] =>
    [maxResults:protected] =>
    [total:protected] =>
    [result:protected] => Array
        (
            [errorMessages] => Array
                (
                )
            [errors] => Array
                (
                    [customfield_10190] => Option value 'Sigapore' is not valid
                    [customfield_10301] => Option value 'We' is not valid
                )
        )
)
```

**Comment by aik099** [comment]
But method name you've changed is called `getIssues` it it returns issues. When there are errors, then no issues are returned and that's absolutely correct behavior.

If you want to get errors you can do 2 things:

1. either use `getResult` and manually look for errors
2. add `getErrors` method that would return errors if any and empty array otherwise

**Comment by aik099** [comment]
I hope you do understand that proposed change would result in `getIssues` method returning an  empty array instead of found issues, when no errors happened 😄

**Comment by mmkader85** [comment]
Ah, yes. Realised it. Confused JIRA issues(Ticket) with errors. Thanks mate.

**Pull request closed without merging**
