### PR TITLE
Bunch of CS fixes

### PR DESCRIPTION
**Pull request by aik099**
We don't have any tests and that's why changes, that are of 2 types:

* not affecting code at all, e.g. whitespaces
* made by automatic clever fixing tools (e.g. PHP_CodeSniffer), e.g. replacing double with single quotes

What's not fixed in there is DocBlocks. I guess they deserve separate PR.

### CODE REVIEW

**Comment by jpastoor** [comment]
I think you can rebase & merge this :+1:

**Comment by aik099** [comment]
Ah, it was good to merge until some recent PRs get merged in. I'll do the rebase then.

**Comment by aik099** [comment]
Rebase version pushed. Ready for review.

**Comment by aik099** [comment]
Turned out, that one PRs were using TABs for indentation instead of SPACEs. I've fixed that as part of my PR as well.

**Pull request merged**
