### PR TITLE
Add getTimeTracking function.

### PR DESCRIPTION
**Pull request by criz**
Otherwise timetracking data is not available in issues.

### CODE REVIEW

**Comment by aik099** [comment]
The `$issue->get('Time Tracking')` would also work, because `get` method is public.

**Comment by criz** [comment]
The get function is only returning fields.

**Comment by aik099** [comment]
But inside your new method you're using that `get` method as well.

**Comment by criz** [comment]
haha, yeah. Sorry, I was confused with this only returning "fields"...

**Pull request closed without merging**
